//EVENTS
export const CREATE_REQUEST = 'CREATE_EVENT_REQUEST'
export const CREATE_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_FAILURE = 'CREATE_EVENT_FAILURE'

export const EVENTS_REQUEST = 'FETCH_EVENTS_REQUEST'
export const EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS'
export const EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE'

export const DELETE_REQUEST = 'DELETE_EVENT_REQUEST'
export const DELETE_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_FAILURE = 'DELETE_EVENT_FAILURE'
