//ODDS
export const ODDS_REQUEST = 'FETCH_ODDS_REQUEST'
export const ODDS_SUCCESS = 'FETCH_ODDS_SUCCESS'
export const ODDS_FAILURE = 'FETCH_ODDS_FAILURE'

//ALERTS
export const ADD_ALERT = 'ADD_ALERT_NOTIFICATION'

//LOADING
export const LOADING_TRUE = 'LOADING_DATA_TRUE'
export const LOADING_FALSE = 'LOADING_DATA_FALSE'
