//USER
export const REGISTER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_USER_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_USER_FAILURE'

export const LOGOUT_SUCCESS = 'LOGOUT_USER_SUCCESS'

export const USER_REQUEST = 'FETCH_USER_REQUEST'
export const USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const USER_FAILURE = 'FETCH_USER_FAILURE'

export const UPDATE_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_FAILURE = 'UPDATE_USER_FAILURE'
